from __future__ import annotations

import argparse
import json
import math
import sys
from copy import deepcopy
from pathlib import Path
from typing import Any

from epistemic_toolbox.concept_equivalence import FACETS, compare, load_json, validate_block

CLOSING_STATUSES = {"CLOSED", "NEAR_CLOSED"}
DISPLAY_CLOSING_STATUSES = {"CLOSED", "NEAR_CLOSED", "COMPATIBLE_EXTENSION"}


def write_json(path: str | Path, data: Any, pretty: bool = True) -> None:
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    Path(path).write_text(json.dumps(data, indent=2 if pretty else None, ensure_ascii=False) + "\n")


def normalized_distance(artifact: dict[str, Any]) -> float:
    return float(artifact.get("closure", {}).get("normalized_distance", math.inf))


def align_origin_to_usage_concept(origin: dict[str, Any], usage: dict[str, Any], adapt_concept_id: bool = True) -> tuple[dict[str, Any], bool]:
    if origin.get("concept_id") == usage.get("concept_id"):
        return origin, False
    if not adapt_concept_id:
        raise ValueError(f"concept_id mismatch: {origin.get('concept_id')} != {usage.get('concept_id')}")
    aligned = deepcopy(origin)
    aligned["bridge_probe_original_concept_id"] = aligned.get("concept_id")
    aligned["concept_id"] = usage["concept_id"]
    aligned["id"] = f"{aligned.get('id', 'origin')}-adapted-to-{usage['concept_id']}"
    aligned["local_context"] = (
        str(aligned.get("local_context", ""))
        + "\n[bridge-probe adaptation] Origin block concept_id was temporarily aligned to the usage concept_id so the existing concept-equivalence engine can measure the lineage edge. This is a measurement adapter, not a claim that the original paper used the same concept label."
    )
    return aligned, True


def block_label(block: dict[str, Any]) -> str:
    paper = block.get("paper", {})
    title = paper.get("title") or block.get("id")
    year = paper.get("year", "?")
    return f"{title} ({year})"


def synthesize_bridge_block(origin: dict[str, Any], usage: dict[str, Any], mask: int, label: str | None = None) -> dict[str, Any]:
    """Create a bridge block by choosing each facet from origin or usage.

    mask bit = 0 means origin facet; mask bit = 1 means usage facet.
    This is intentionally deterministic. It does not pretend to discover a real
    source. It discovers the nearest block-shape that would reduce/close the
    measured gap, which tells us what evidence to go hunting for.
    """
    chosen: dict[str, str] = {}
    facets: dict[str, list[str]] = {}
    for idx, facet in enumerate(FACETS):
        use_usage = bool(mask & (1 << idx))
        chosen[facet] = "usage" if use_usage else "origin"
        source = usage if use_usage else origin
        facets[facet] = list(source.get("facets", {}).get(facet, []))

    origin_span = deepcopy(origin.get("spans", [{}])[0])
    usage_span = deepcopy(usage.get("spans", [{}])[0])
    origin_span.setdefault("locator", "origin")
    usage_span.setdefault("locator", "usage")

    origin_bits = sum(1 for src in chosen.values() if src == "origin")
    usage_bits = len(FACETS) - origin_bits
    bridge_id = label or f"bridge-candidate-{origin.get('concept_id','concept')}-{mask:03d}"
    return {
        "schema_version": "mindware.concept.block.v1",
        "id": bridge_id,
        "concept_id": origin["concept_id"],
        "role": "bridge",
        "paper": {
            "title": f"Synthetic bridge probe: {block_label(origin)} → {block_label(usage)}",
            "authors": ["Epistemic Toolbox bridge-probe"],
            "year": usage.get("paper", {}).get("year", origin.get("paper", {}).get("year")),
            "uri": "synthetic://bridge-probe/facet-hybrid",
        },
        "spans": [
            {"locator": f"origin::{origin_span.get('locator','origin')}", "quote": origin_span.get("quote", origin.get("quoted_definition", ""))},
            {"locator": f"usage::{usage_span.get('locator','usage')}", "quote": usage_span.get("quote", usage.get("quoted_definition", ""))},
        ],
        "quoted_definition": usage.get("quoted_definition") if chosen["definition"] == "usage" else origin.get("quoted_definition"),
        "local_context": (
            "Synthetic bridge candidate generated by facet-hybrid search. "
            f"Origin facets: {origin_bits}; usage facets: {usage_bits}. "
            "This is a search target, not evidence. Find or write a real block that occupies this shape."
        ),
        "facets": facets,
        "known_limits": [
            "Synthetic candidate; not a source receipt.",
            "A low gap only says this facet mix would reduce measured drift.",
            "Human review must replace synthetic spans with real source spans before treating as lineage.",
        ],
        "bridge_probe": {
            "mask": mask,
            "facet_sources": chosen,
            "origin_block": origin.get("id"),
            "usage_block": usage.get("id"),
        },
    }


def evaluate_candidate(origin: dict[str, Any], usage: dict[str, Any], mask: int) -> dict[str, Any]:
    bridge = synthesize_bridge_block(origin, usage, mask)
    validate_block(bridge, Path(f"synthetic-mask-{mask}"))
    left = compare(origin, bridge)
    right = compare(bridge, usage)
    return {
        "mask": mask,
        "facet_sources": bridge["bridge_probe"]["facet_sources"],
        "bridge_block": bridge,
        "left_status": left["status"],
        "right_status": right["status"],
        "left_distance": normalized_distance(left),
        "right_distance": normalized_distance(right),
        "max_hop_distance": max(normalized_distance(left), normalized_distance(right)),
        "total_hop_distance": normalized_distance(left) + normalized_distance(right),
        "left_artifact": left,
        "right_artifact": right,
        "strict_closes_left": left["status"] == "CLOSED",
        "strict_closes_right": right["status"] == "CLOSED",
        "closes_left": left["status"] in CLOSING_STATUSES,
        "closes_right": right["status"] in CLOSING_STATUSES,
        "display_closes_left": left["status"] in DISPLAY_CLOSING_STATUSES,
        "display_closes_right": right["status"] in DISPLAY_CLOSING_STATUSES,
    }


def rank_candidates(results: list[dict[str, Any]], direct_distance: float) -> list[dict[str, Any]]:
    def key(r: dict[str, Any]) -> tuple[Any, ...]:
        any_close = r["closes_left"] or r["closes_right"]
        both_lower = r["left_distance"] < direct_distance and r["right_distance"] < direct_distance
        return (
            0 if any_close else 1,
            0 if both_lower else 1,
            r["max_hop_distance"],
            r["total_hop_distance"],
            abs(r["left_distance"] - r["right_distance"]),
            r["mask"],
        )
    return sorted(results, key=key)


def probe_pair(origin_path: str | Path, usage_path: str | Path, top: int = 8, adapt_concept_id: bool = True) -> dict[str, Any]:
    origin = load_json(Path(origin_path))
    usage = load_json(Path(usage_path))
    validate_block(origin, Path(origin_path))
    validate_block(usage, Path(usage_path))
    adapted = False
    origin, adapted = align_origin_to_usage_concept(origin, usage, adapt_concept_id=adapt_concept_id)
    direct = compare(origin, usage)
    direct_distance = normalized_distance(direct)
    results = [evaluate_candidate(origin, usage, mask) for mask in range(1 << len(FACETS))]
    ranked = rank_candidates(results, direct_distance)
    best = ranked[0]
    return {
        "schema_version": "epistemic.bridge.probe.v1",
        "origin_path": str(origin_path),
        "usage_path": str(usage_path),
        "concept_id": origin["concept_id"],
        "concept_id_adapted": adapted,
        "direct_status": direct["status"],
        "direct_distance": direct_distance,
        "direct_artifact": direct,
        "searched_candidates": len(results),
        "strict_closing_candidates": sum(1 for r in results if r["strict_closes_left"] or r["strict_closes_right"]),
        "near_closing_candidates": sum(1 for r in results if r["closes_left"] or r["closes_right"]),
        "lower_max_candidates": sum(1 for r in results if r["max_hop_distance"] < direct_distance),
        "best": summarize_candidate(best, direct_distance),
        "top_candidates": [summarize_candidate(r, direct_distance) for r in ranked[:top]],
    }


def summarize_candidate(r: dict[str, Any], direct_distance: float) -> dict[str, Any]:
    return {
        "mask": r["mask"],
        "facet_sources": r["facet_sources"],
        "left_status": r["left_status"],
        "right_status": r["right_status"],
        "left_distance": round(r["left_distance"], 6),
        "right_distance": round(r["right_distance"], 6),
        "max_hop_distance": round(r["max_hop_distance"], 6),
        "total_hop_distance": round(r["total_hop_distance"], 6),
        "improves_max": r["max_hop_distance"] < direct_distance,
        "max_reduction": round(direct_distance - r["max_hop_distance"], 6),
        "closes_left": r["closes_left"],
        "closes_right": r["closes_right"],
        "strict_closes_left": r["strict_closes_left"],
        "strict_closes_right": r["strict_closes_right"],
    }


def probe_index(index_path: str | Path, outdir: str | Path, top: int = 8, write_blocks: int = 3) -> dict[str, Any]:
    index_path = Path(index_path)
    outdir = Path(outdir)
    idx = load_json(index_path)
    outdir.mkdir(parents=True, exist_ok=True)
    pair_summaries = []
    all_best_blocks = []
    for i, pair in enumerate(idx.get("origin_pairs", []), 1):
        probe = probe_pair(pair["origin_block"], pair["usage_block"], top=top)
        stem = f"{i:02d}.{pair['origin_source_id']}.to.{pair['usage_concept_id']}"
        probe_path = outdir / "pairs" / f"{stem}.bridge-probe.json"
        write_json(probe_path, probe)
        # Recreate top bridge block files without embedding the large artifacts in the pair summary.
        origin = load_json(Path(pair["origin_block"]))
        usage = load_json(Path(pair["usage_block"]))
        origin, _ = align_origin_to_usage_concept(origin, usage, adapt_concept_id=True)
        for rank, cand in enumerate(probe["top_candidates"][:write_blocks], 1):
            block = synthesize_bridge_block(origin, usage, cand["mask"], label=f"bridge-candidate-{stem}-{rank:02d}")
            block_path = outdir / "bridge-blocks" / f"{stem}.rank-{rank:02d}.concept-block.json"
            write_json(block_path, block)
            if rank == 1:
                all_best_blocks.append(str(block_path))
        pair_summaries.append({
            "pair_index": i,
            "origin_source_id": pair.get("origin_source_id"),
            "usage_concept_id": pair.get("usage_concept_id"),
            "probe_path": str(probe_path),
            "direct_status": probe["direct_status"],
            "direct_distance": round(probe["direct_distance"], 6),
            "strict_closing_candidates": probe["strict_closing_candidates"],
            "near_closing_candidates": probe["near_closing_candidates"],
            "lower_max_candidates": probe["lower_max_candidates"],
            "best": probe["best"],
        })
    pair_summaries.sort(key=lambda p: (not p["best"]["improves_max"], p["best"]["max_hop_distance"], -p["best"]["max_reduction"]))
    summary = {
        "schema_version": "epistemic.bridge.probe.index.v1",
        "source_index": str(index_path),
        "pairs": len(pair_summaries),
        "total_strict_closing_candidates": sum(p["strict_closing_candidates"] for p in pair_summaries),
        "total_near_closing_candidates": sum(p["near_closing_candidates"] for p in pair_summaries),
        "pairs_with_lower_max_candidate": sum(1 for p in pair_summaries if p["best"]["improves_max"]),
        "best_bridge_blocks": all_best_blocks,
        "ranked_pairs": pair_summaries,
    }
    write_json(outdir / "bridge-probe-summary.json", summary)
    write_report(outdir / "bridge-probe-report.md", summary)
    return summary


def write_report(path: str | Path, summary: dict[str, Any]) -> None:
    lines = [
        "# Bridge Probe Report",
        "",
        "Goal: find the closest synthetic bridge block that closes one side of a drift edge and/or lowers the maximum two-hop drift.",
        "",
        f"Pairs: {summary['pairs']}",
        f"Total strict closing candidates: {summary['total_strict_closing_candidates']}",
        f"Total near closing candidates: {summary['total_near_closing_candidates']}",
        f"Pairs with lower max-hop candidate: {summary['pairs_with_lower_max_candidate']}",
        "",
        "Important: generated bridge blocks are search targets, not evidence. Replace synthetic spans with real source spans before claiming lineage closure.",
        "",
        "## Ranked pairs",
        "",
    ]
    for p in summary["ranked_pairs"]:
        b = p["best"]
        lines.extend([
            f"### {p['origin_source_id']} → {p['usage_concept_id']}",
            "",
            f"Direct: {p['direct_status']} d={p['direct_distance']}",
            f"Best bridge: left={b['left_status']} d={b['left_distance']} / right={b['right_status']} d={b['right_distance']} / max={b['max_hop_distance']} / reduction={b['max_reduction']}",
            f"Improves max drift: {b['improves_max']}",
            f"Facet sources: {json.dumps(b['facet_sources'], ensure_ascii=False)}",
            f"Probe: `{p['probe_path']}`",
            "",
        ])
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    Path(path).write_text("\n".join(lines) + "\n")


def main(argv: list[str] | None = None) -> int:
    if argv is None:
        argv = sys.argv[1:]
    parser = argparse.ArgumentParser(description="Search for synthetic bridge blocks that close or reduce drift between concept blocks.")
    sub = parser.add_subparsers(dest="cmd", required=True)
    p = sub.add_parser("pair", help="Probe one origin/usage block pair")
    p.add_argument("origin")
    p.add_argument("usage")
    p.add_argument("--out", required=True)
    p.add_argument("--top", type=int, default=8)
    i = sub.add_parser("index", help="Probe every origin_pair in a lineage-block-pairs.index.json")
    i.add_argument("index")
    i.add_argument("--outdir", required=True)
    i.add_argument("--top", type=int, default=8)
    i.add_argument("--write-blocks", type=int, default=3)
    args = parser.parse_args(argv)
    if args.cmd == "pair":
        result = probe_pair(args.origin, args.usage, top=args.top)
        write_json(args.out, result)
        print(args.out)
        return 0
    if args.cmd == "index":
        summary = probe_index(args.index, args.outdir, top=args.top, write_blocks=args.write_blocks)
        print(Path(args.outdir) / "bridge-probe-summary.json")
        print(f"pairs={summary['pairs']} lower_max={summary['pairs_with_lower_max_candidate']}")
        return 0
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
